// products.js
export const products = [
// Abarrotes
{ id: 1, name: "Ajo en polvo", description: "Gourmet", price: 1200, image: "/imagenes/abarrotes/aba1.jpg" },
{ id: 2, name: "Aliño completo", description: "Gourmet", price: 1200, image: "/imagenes/abarrotes/aba2.jpg" },
{ id: 3, name: "Arroz G1 Miraflores", description: "1Kg", price: 1200, image: "/imagenes/abarrotes/aba3.jpg" },
{ id: 4, name: "Arroz G2 Tucapel", description: "1Kg", price: 1200, image: "/imagenes/abarrotes/aba4.jpg" },
{ id: 5, name: "Arroz Villa Oliva", description: "Sin gluten 1Kg", price: 1200, image: "/imagenes/abarrotes/aba5.jpg" },
{ id: 6, name: "Lomito atun en aceite", description: "Robinson Crusoe", price: 1200, image: "/imagenes/abarrotes/aba6.jpg" },
{ id: 7, name: "Lomito atun en agua", description: "Robinson Crusoe", price: 1200, image: "/imagenes/abarrotes/aba7.jpg" },
{ id: 8, name: "Azucar flor", description: "Iansa 1Kg", price: 1200, image: "/imagenes/abarrotes/aba8.jpg" },
{ id: 9, name: "Azucar blanca", description: "Iansa 1Kg", price: 1200, image: "/imagenes/abarrotes/aba9.jpg" },
{ id: 10, name: "Azucar rubia", description: "Iansa 700g", price: 1200, image: "/imagenes/abarrotes/aba10.jpg" },
{ id: 11, name: "Bolo de naranja", description: "Schar", price: 1200, image: "/imagenes/abarrotes/aba11.jpg" },
{ id: 12, name: "Camarones premium", description: "Gag 1Kg", price: 1200, image: "/imagenes/abarrotes/aba12.jpg" },
{ id: 13, name: "Caracoquesos", description: "Carozzi", price: 1200, image: "/imagenes/abarrotes/aba13.jpg" },
{ id: 14, name: "Choclo grano congelado", description: "Minuto verde 1Kg", price: 1200, image: "/imagenes/abarrotes/aba14.jpg" },
{ id: 15, name: "Choritos", description: "Robinson Crusoe", price: 1200, image: "/imagenes/abarrotes/aba15.jpg" },
{ id: 16, name: "ColaCao instantaneo", description: "Chocolate 180g", price: 1200, image: "/imagenes/abarrotes/aba16.jpg" },
{ id: 17, name: "Crema de leche", description: "Nestle 157g", price: 1200, image: "/imagenes/abarrotes/aba17.jpg" },
{ id: 18, name: "Crema de leche", description: "Nestle 236", price: 1200, image: "/imagenes/abarrotes/aba18.jpg" },
{ id: 19, name: "Endulzante Stevia", description: "Daily 270ml", price: 1200, image: "/imagenes/abarrotes/aba19.jpg" },
{ id: 20, name: "Dulce de leche", description: "Manfrey 400g", price: 1200, image: "/imagenes/abarrotes/aba20.jpg" },
{ id: 21, name: "Duraznos mitades", description: "Esmeralda 425g", price: 1200, image: "/imagenes/abarrotes/aba21.jpg" },
{ id: 22, name: "Duraznos cubitos", description: "Wasil", price: 1200, image: "/imagenes/abarrotes/aba22.jpg" },
{ id: 23, name: "Espirales", description: "Carozzi 400g", price: 1200, image: "/imagenes/abarrotes/aba23.jpg" },
{ id: 24, name: "Gnochi de papa", description: "Trattoria 500g", price: 1200, image: "/imagenes/abarrotes/aba24.jpg" },
{ id: 25, name: "Harina con polvo", description: "Selecta", price: 1200, image: "/imagenes/abarrotes/aba25.jpg" },
{ id: 26, name: "Harina sin gluten", description: "Schar", price: 1200, image: "/imagenes/abarrotes/aba26.jpg" },
{ id: 27, name: "Harina sin polvo", description: "Selecta", price: 1200, image: "/imagenes/abarrotes/aba27.jpg" },
{ id: 28, name: "Ketchup", description: "Heinz", price: 1200, image: "/imagenes/abarrotes/aba28.jpg" },
{ id: 29, name: "Lasaña tradicional", description: "Carozzi", price: 1200, image: "/imagenes/abarrotes/aba29.jpg" },
{ id: 30, name: "Leche condensada", description: "Nestle", price: 1200, image: "/imagenes/abarrotes/aba30.jpg" },
{ id: 31, name: "Leche evaporada", description: "Nestle", price: 1200, image: "/imagenes/abarrotes/aba31.jpg" },
{ id: 32, name: "Maizena", description: "Original", price: 1200, image: "/imagenes/abarrotes/aba32.jpg" },
{ id: 33, name: "Manjar tradicional", description: "Colun", price: 1200, image: "/imagenes/abarrotes/aba33.jpg" },
{ id: 34, name: "Mantequilla de mani", description: "El buho", price: 1200, image: "/imagenes/abarrotes/aba34.jpg" },
{ id: 35, name: "Mantequilla untable", description: "Colun", price: 1200, image: "/imagenes/abarrotes/aba35.jpg" },
{ id: 36, name: "Margarina Mix", description: "Soprole", price: 1200, image: "/imagenes/abarrotes/aba36.jpg" },
{ id: 37, name: "Maruchan instant lunch", description: "Sabor a pollo", price: 1200, image: "/imagenes/abarrotes/aba37.jpg" },
{ id: 38, name: "Mayonesa", description: "Kraft 394g", price: 1200, image: "/imagenes/abarrotes/aba38.jpg" },
{ id: 39, name: "Mermelada sin azucar", description: "En linea", price: 1200, image: "/imagenes/abarrotes/aba39.jpg" },
{ id: 40, name: "Mermelada ciruela", description: "Baggio", price: 1200, image: "/imagenes/abarrotes/aba40.jpg" },
{ id: 41, name: "Mermelada damasco", description: "Baggio", price: 1200, image: "/imagenes/abarrotes/aba41.jpg" },
{ id: 42, name: "Mermelada frutos del sur", description: "Watts", price: 1200, image: "/imagenes/abarrotes/aba42.jpg" },
{ id: 43, name: "Mermelada multi frutal", description: "Baggio", price: 1200, image: "/imagenes/abarrotes/aba43.jpg" },
{ id: 44, name: "Mostaza", description: "Heinz", price: 1200, image: "/imagenes/abarrotes/aba44.jpg" },
{ id: 45, name: "Oregano entero", description: "Gourmet", price: 1200, image: "/imagenes/abarrotes/aba45.jpg" },
{ id: 46, name: "Palmitos rodaja", description: "Esmeralda", price: 1200, image: "/imagenes/abarrotes/aba46.jpg" },
{ id: 47, name: "Pan molde blanco", description: "Ideal 550g", price: 1200, image: "/imagenes/abarrotes/aba47.jpg" },
{ id: 48, name: "Pan hambruguesa", description: "02 unidades  Schar", price: 1200, image: "/imagenes/abarrotes/aba48.jpg" },
{ id: 49, name: "Pan Hot dog", description: "08 unidades Ideal", price: 1200, image: "/imagenes/abarrotes/aba49.jpg" },
{ id: 50, name: "Pan molde sin gluten", description: "Schar 200g", price: 1200, image: "/imagenes/abarrotes/aba50.jpg" },
{ id: 51, name: "Pasta arroz sin gluten", description: "Trattoria 250g", price: 1200, image: "/imagenes/abarrotes/aba51.jpg" },
{ id: 52, name: "Pimienta negra molida", description: "Gourmet", price: 1200, image: "/imagenes/abarrotes/aba52.jpg" },
{ id: 53, name: "Polvos para hornear", description: "Royal", price: 1200, image: "/imagenes/abarrotes/aba53.jpg" },
{ id: 54, name: "Pure de papas", description: "Maggi", price: 1200, image: "/imagenes/abarrotes/aba54.jpg" },
{ id: 55, name: "Pure de tomates sin gluten", description: "Baggio 530g", price: 1200, image: "/imagenes/abarrotes/aba55.jpg" },
{ id: 56, name: "Queso Cheddar", description: "Kraft", price: 1200, image: "/imagenes/abarrotes/aba56.jpg" },
{ id: 57, name: "Queso Philadelphia", description: "Original", price: 1200, image: "/imagenes/abarrotes/aba57.jpg" },
{ id: 58, name: "Rapiditas", description: "Ideal", price: 1200, image: "/imagenes/abarrotes/aba58.jpg" },
{ id: 59, name: "Ravioles 4 quesos", description: "La Salteña", price: 1200, image: "/imagenes/abarrotes/aba59.jpg" },
{ id: 60, name: "Rigatoni", description: "Carozzi 400g", price: 1200, image: "/imagenes/abarrotes/aba60.jpg" },
{ id: 61, name: "Salame ahumado", description: "Pf 100g", price: 1200, image: "/imagenes/abarrotes/aba61.jpg" },
{ id: 62, name: "Salsa barbacue", description: "Kraft", price: 1200, image: "/imagenes/abarrotes/aba62.jpg" },
{ id: 63, name: "Salsa tomate", description: "Doña clara 200g", price: 1200, image: "/imagenes/abarrotes/aba63.jpg" },
{ id: 64, name: "Salsa tomate", description: "Pomarola Carozzi 200g", price: 1200, image: "/imagenes/abarrotes/aba64.jpg" },
{ id: 65, name: "Salsa de soya", description: "Gourmet", price: 1200, image: "/imagenes/abarrotes/aba65.jpg" },
{ id: 66, name: "Salsa tomate", description: "Tuco carne", price: 1200, image: "/imagenes/abarrotes/aba66.jpg" },
{ id: 67, name: "Tallarines 77", description: "Lucchetti 400g", price: 1200, image: "/imagenes/abarrotes/aba67.jpg" },
{ id: 68, name: "Té ceylan", description: "Dilmah 20 bolsitas", price: 1200, image: "/imagenes/abarrotes/aba68.jpg" },
{ id: 69, name: "Té ceylan", description: "Supremo 20 bolsitas", price: 1200, image: "/imagenes/abarrotes/aba69.jpg" },
{ id: 70, name: "Té verde", description: "Thurson 20 bolsitas", price: 1200, image: "/imagenes/abarrotes/aba70.jpg" },

// Aceites
{ id: 71, name: "Aceite de Oliva", description: "Aceite puro, extra oliva", price: 4500, image: "/imagenes/aceites/ace1.jpg" },
{ id: 72, name: "Aceite de Oliva", description: "Aceite puro, extra virgen", price: 4500, image: "/imagenes/aceites/ace2.jpg" },
{ id: 73, name: "Aceite Vegetal", description: "Aceite vegetal, con canola", price: 4500, image: "/imagenes/aceites/ace3.jpg" },
{ id: 74, name: "Aceite Vegano", description: "Aceite de Lino, bio-organic", price: 4500, image: "/imagenes/aceites/ace4.jpg" },
{ id: 75, name: "Aceite Vegano", description: "Aceite de Sesamo, bio-organic", price: 4500, image: "/imagenes/aceites/ace5.jpg" },

// Bebestibles
{ id: 76, name: "Jugo Mango-Maracuya", description: "Gran seleccion de Watts 1L", price: 800, image: "/imagenes/bebestibles/bebe1.jpg" },
{ id: 77, name: "Jugo Naranja Valencia", description: "Gran seleccion de Watts 1L", price: 800, image: "/imagenes/bebestibles/bebe2.jpg" },
{ id: 78, name: "Limonada Love Lemon", description: "Sabor original 385ml", price: 800, image: "/imagenes/bebestibles/bebe3.jpg" },
{ id: 79, name: "Limonada Love Lemon", description: "Sabor blue 385ml", price: 800, image: "/imagenes/bebestibles/bebe4.jpg" },
{ id: 80, name: "Limonada Love Lemon", description: "Sabor pink 385ml", price: 800, image: "/imagenes/bebestibles/bebe5.jpg" },
{ id: 81, name: "Jugo Durazno", description: "Watts 1.5L", price: 800, image: "/imagenes/bebestibles/bebe6.jpg" },
{ id: 82, name: "Coca-Cola", description: "Sabor original 1.5L", price: 800, image: "/imagenes/bebestibles/bebe7.jpg" },
{ id: 83, name: "Jugo three pack vivo", description: "Fruta y vegetales 190ml", price: 800, image: "/imagenes/bebestibles/bebe8.jpg" },
{ id: 84, name: "Jugo three pack vivo", description: "Fruta y vegetales 190ml", price: 800, image: "/imagenes/bebestibles/bebe9.jpg" },

// Café
{ id: 85, name: "Café Lucaffe classic", description: "1Kg", price: 3000, image: "/imagenes/cafe/caf1.jpg" },
{ id: 86, name: "Café Bacio Nero Espresso", description: "1Kg", price: 3000, image: "/imagenes/cafe/caf2.jpg" },
{ id: 87, name: "Café La Emozione", description: "1Kg", price: 3000, image: "/imagenes/cafe/caf3.jpg" },
{ id: 88, name: "Café Garibaldi intenso", description: "1Kg", price: 3000, image: "/imagenes/cafe/caf4.jpg" },
{ id: 89, name: "Café Marconi Culligan", description: "1Kg", price: 3000, image: "/imagenes/cafe/caf5.jpg" },
{ id: 90, name: "Café Juan Valdez variedades", description: "Variedad de sabores", price: 3000, image: "/imagenes/cafe/caf6.jpg" },
{ id: 91, name: "Café Nescafe tradicional", description: "50g", price: 3000, image: "/imagenes/cafe/caf7.jpg" },
{ id: 92, name: "Café Nescafe Moka", description: "Caja con 8 sobres", price: 3000, image: "/imagenes/cafe/caf8.jpg" },
{ id: 93, name: "Café Vainilla Latte", description: "Caja con 8 sobres", price: 3000, image: "/imagenes/cafe/caf9.jpg" },

// Cereales
{ id: 94, name: "Cereal Pillows", description: "Exquisitos 350g", price: 1000, image: "/imagenes/cereales/cer1.jpg" },
{ id: 95, name: "Cereal Milo", description: "Exquisitos 300g", price: 1000, image: "/imagenes/cereales/cer2.jpg" },
{ id: 96, name: "Cereal Chocapic", description: "Exquisitos 330g", price: 1000, image: "/imagenes/cereales/cer3.jpg" },
{ id: 97, name: "Cereal Zucaritas", description: "Exquisitos 730g", price: 1000, image: "/imagenes/cereales/cer4.jpg" },
{ id: 98, name: "Cereal Avena Vivo", description: "Exquisitos 800g", price: 1000, image: "/imagenes/cereales/cer5.jpg" },

// Huevos
{ id: 99, name: "Huevos Frescos", description: "Huevos de gallina", price: 2500, image: "/imagenes/huevos/huevoseb.jpg" },
{ id: 100, name: "Huevos Frescos", description: "Huevos de gallina", price: 2500, image: "/imagenes/huevos/huevosec.jpg" },
{ id: 101, name: "Huevos Frescos", description: "Huevos de gallina", price: 2500, image: "/imagenes/huevos/huevospb.jpg" },
{ id: 102, name: "Huevos Frescos", description: "Huevos de gallina", price: 2500, image: "/imagenes/huevos/huevospc.jpg" },

// Leche
{ id: 103, name: "Pack Leche Semi descremada", description: "Soprole 12 unidades", price: 2000, image: "/imagenes/leche/lech1.jpg" },
{ id: 104, name: "Pack Leche Entera", description: "Soprole 12 unidades", price: 2000, image: "/imagenes/leche/lech2.jpg" },
{ id: 105, name: "Pack Leche Descremada", description: "Soprole 12 unidades", price: 2000, image: "/imagenes/leche/lech3.jpg" },
{ id: 106, name: "Leche Semi descremada", description: "Soprole 1 Litro", price: 2000, image: "/imagenes/leche/lech4.jpg" },
{ id: 107, name: "Leche Entera", description: "Soprole 1 Litro", price: 2000, image: "/imagenes/leche/lech5.jpg" },
{ id: 108, name: "Leche Zero Lacteo Semi", description: "Soprole 1 Litro", price: 2000, image: "/imagenes/leche/lech6.jpg" },
{ id: 109, name: "Leche Descremada", description: "Soprole 1 Litro", price: 2000, image: "/imagenes/leche/lech7.jpg" },
{ id: 110, name: "Leche Zero Lacteo Descremada", description: "Soprole 1 Litro", price: 2000, image: "/imagenes/leche/lech8.jpg" },
{ id: 111, name: "Leche Almendras original", description: "Tasty 1 Litro", price: 2000, image: "/imagenes/leche/lech9.jpg" },
{ id: 112, name: "Leche en polvo Entera", description: "Colun 900g", price: 2000, image: "/imagenes/leche/lech10.jpg" },
{ id: 113, name: "Pack leche individual entera", description: "Colun 6x200cc", price: 2000, image: "/imagenes/leche/lech11.jpg" },
{ id: 114, name: "Pack leche individual chocolate", description: "Colun 6x200cc", price: 2000, image: "/imagenes/leche/lech12.jpg" },
{ id: 115, name: "Pack leche individual frutilla", description: "Colun 6x200cc", price: 2000, image: "/imagenes/leche/lech13.jpg" },

// Limpieza
{ id: 116, name: "Detergente concentrado Dapper", description: "Hipoalergenico 3L", price: 2500, image: "/imagenes/limpieza/lim1.jpg" },
{ id: 117, name: "Cloro Gel Igenix", description: "Aroma Lavanda 900ml", price: 2500, image: "/imagenes/limpieza/lim2.jpg" },
{ id: 118, name: "Cif crema", description: "Multiuso", price: 2500, image: "/imagenes/limpieza/lim3.jpg" },
{ id: 119, name: "Jabon liquido Ballerina", description: "750ml", price: 2500, image: "/imagenes/limpieza/lim4.jpg" },
{ id: 120, name: "Paño esponja Virutex", description: "6 Paños", price: 2500, image: "/imagenes/limpieza/lim5.jpg" },
{ id: 121, name: "Esponja generica", description: "03 Unidades", price: 2500, image: "/imagenes/limpieza/lim6.jpg" },

// Snacks
{ id: 122, name: "Pack Tika rice pop", description: "05 unidades", price: 1500, image: "/imagenes/snacks/sna1.jpg" },
{ id: 123, name: "Mizos", description: "Chocolate naranja", price: 1500, image: "/imagenes/snacks/sna2.jpg" },
{ id: 124, name: "Puri", description: "Chocolate", price: 1500, image: "/imagenes/snacks/sna3.jpg" },
{ id: 125, name: "Puri", description: "Garbanzo mani", price: 1500, image: "/imagenes/snacks/sna4.jpg" },
{ id: 126, name: "Puri", description: "Garbanzo queso", price: 1500, image: "/imagenes/snacks/sna5.jpg" },
{ id: 127, name: "Puri", description: "Tomate albaca", price: 1500, image: "/imagenes/snacks/sna6.jpg" },
{ id: 128, name: "Mizos", description: "Yogurth frutilla", price: 1500, image: "/imagenes/snacks/sna7.jpg" },
{ id: 129, name: "Mizos", description: "Chocolate", price: 1500, image: "/imagenes/snacks/sna8.jpg" },
{ id: 130, name: "Obsesion", description: "Costa", price: 1500, image: "/imagenes/snacks/sna9.jpg" },
{ id: 131, name: "Braunichoc", description: "Nutrabien", price: 1500, image: "/imagenes/snacks/sna10.jpg" },
{ id: 132, name: "Cereal bar", description: "Costa", price: 1500, image: "/imagenes/snacks/sna11.jpg" },
{ id: 133, name: "Choco arroz", description: "Original", price: 1500, image: "/imagenes/snacks/sna12.jpg" },
{ id: 134, name: "Chococolate Costa rama", description: "Costa", price: 1500, image: "/imagenes/snacks/sna13.jpg" },
{ id: 135, name: "Chococolate Trencito", description: "Nestle", price: 1500, image: "/imagenes/snacks/sna14.jpg" },
{ id: 136, name: "Doritos", description: "Original", price: 1500, image: "/imagenes/snacks/sna15.jpg" },
{ id: 137, name: "Galleta Bon o Bon", description: "Original", price: 1500, image: "/imagenes/snacks/sna16.jpg" },
{ id: 138, name: "Galletas sin gluten", description: "Gullon 200g", price: 1500, image: "/imagenes/snacks/sna17.jpg" },
{ id: 139, name: "Galletas Selz cracker", description: "Original", price: 1500, image: "/imagenes/snacks/sna18.jpg" },
{ id: 140, name: "Galletas Donuts", description: "Costa", price: 1500, image: "/imagenes/snacks/sna19.jpg" },
{ id: 141, name: "Galletas Gretel", description: "Costa", price: 1500, image: "/imagenes/snacks/sna20.jpg" },
{ id: 142, name: "Galletas Tuareg", description: "Costa", price: 1500, image: "/imagenes/snacks/sna21.jpg" },
{ id: 143, name: "Galletas Vino", description: "Costa", price: 1500, image: "/imagenes/snacks/sna22.jpg" },
{ id: 144, name: "Mankeke Marinela", description: "06 unidades", price: 1500, image: "/imagenes/snacks/sna23.jpg" },
{ id: 145, name: "Marsh Mallows", description: "Ambrosoli", price: 1500, image: "/imagenes/snacks/sna24.jpg" },
{ id: 146, name: "Nutella Go", description: "Original", price: 1500, image: "/imagenes/snacks/sna25.jpg" },
{ id: 147, name: "Galletas Oreo sin gluten", description: "Original", price: 1500, image: "/imagenes/snacks/sna26.jpg" },
{ id: 148, name: "Papas fritas Lays", description: "Corte americano", price: 1500, image: "/imagenes/snacks/sna27.jpg" },
{ id: 149, name: "Papas fritas Marco Polo", description: "Rusticas", price: 1500, image: "/imagenes/snacks/sna28.jpg" },
{ id: 150, name: "Papas fritas tarro", description: "Lays Stax", price: 1500, image: "/imagenes/snacks/sna29.jpg" },
{ id: 151, name: "Pinguinos Marinela", description: "04 unidades", price: 1500, image: "/imagenes/snacks/sna30.jpg" },
{ id: 152, name: "Ramitas queso", description: "Evercrisp", price: 1500, image: "/imagenes/snacks/sna31.jpg" },
{ id: 153, name: "Mini Tika rice pop", description: "Chocolate berries", price: 1500, image: "/imagenes/snacks/sna32.jpg" },
{ id: 154, name: "Takis fuego", description: "Original", price: 1500, image: "/imagenes/snacks/sna33.jpg" },

// Verduras
{ id: 155, name: "Zanahoria cubos", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver1.jpg" },
{ id: 156, name: "Acelga picada", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver2.jpg" },
{ id: 157, name: "Apio media luna", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver3.jpg" },
{ id: 158, name: "Berro", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver4.jpg" },
{ id: 159, name: "Betarraga cubos", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver5.jpg" },
{ id: 160, name: "Betarraga enteras", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver6.jpg" },
{ id: 161, name: "Betarraga juliana", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver7.jpg" },
{ id: 162, name: "Cebolla entera", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver8.jpg" },
{ id: 163, name: "Cebolla pluma", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver9.jpg" },
{ id: 164, name: "Ciboulette", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver10.jpg" },
{ id: 165, name: "Espinaca picada", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver11.jpg" },
{ id: 166, name: "Lechuga escarola", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver12.jpg" },
{ id: 167, name: "Lechuga costina", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver13.jpg" },
{ id: 168, name: "Lechuga lollo rosa", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver14.jpg" },
{ id: 169, name: "Papas baston", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver15.jpg" },
{ id: 170, name: "Papas cubo", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver16.jpg" },
{ id: 171, name: "Papas entera", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver17.jpg" },
{ id: 172, name: "Cilantro", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver18.jpg" },
{ id: 173, name: "Repollo blanco", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver19.jpg" },
{ id: 174, name: "Repollo morado", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver20.jpg" },
{ id: 175, name: "Zanahoria entera", description: "Muchos restaurantes lo avalan, sacar del envase y disfrutar", price: 1800, image: "/imagenes/verduras/ver21.jpg" }
];
